const inquirer = require('inquirer');
const fs = require('fs');
var answers = {
    name: undefined,
    author:undefined,
    description:undefined,
    install:undefined,
    license:undefined,
    email:  undefined,
    contributors: [],
    tests: [],
    github: undefined
 };

function init(){
    getFirstAnswers();
    // getContributors();
    // getTests();
    // generateReadme();
}

 function getFirstAnswers() { 
inquirer
  .prompt([
    {
        type: 'input',
        name: 'name',
        message: 'Project Name?',
      },
    {
      type: 'input',
      name: 'author',
      message: 'Project Author Name?',
    },
    {
      type: 'input',
      message: 'Give a short Description of your Project',
      name: 'description',
    },
    {
        type: 'input',
        name: 'install',
        message: 'What are the installation instructions?',
    },
    {
        type: 'input',
        name: 'usage',
        message: 'What are the usage instructions?',
    },
    {
        type: 'list',
        name: 'license',
        message: 'Select the License for this Project',
        choices:['MIT','GNU','Eclipse']
    },
    {
        type: 'input',
        name: 'email',
        message: 'Email?',
    },
    {
        type: 'input',
        name: 'github',
        message: 'Github Username?',
    }
  ])
  .then((data) => {
    answers['name']=data.name;
    answers['author']=data.author;
    answers['description']=data.description;
    answers['license']=data.license;
    answers['email']=data.email;
    answers['github']=data.github;
    getContributors();
  });
}

async function getContributors () {  
  inquirer
  .prompt([
    {
        type: "input",
        name: "contributor",
        message: "Add a Contributor",
      },
      {
        type: "confirm",
        name: "is_finished",
        message: "Are you done?",
      }
])
.then((data) => {
    if (data.is_finished) {
        if (data.contributor){
            answers.contributors.push(data.contributor)
          }
        getTests();
      } else {
          if (data.contributor){
            answers.contributors.push(data.contributor)
            return getContributors()
      }
}
});
}


async function getTests(){
    inquirer
    .prompt([
      {
          type: "input",
          name: "test",
          message: "Add a Test",
        },
        {
          type: "confirm",
          name: "is_finished",
          message: "Are you done?",
        }
  ])
  .then((data) => {
      if (data.is_finished) {
          if (data.test){
              answers.tests.push(data.test)
            }
            generateReadme();
        } else {
            if (data.test){
              answers.tests.push(data.test)
              return getTests();
            }
        }
  });
}
function generateReadme() {

        const filename = `README-Generated.md`;
        const mit='![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)'
        const gnu='![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)'
        const eclipse='![License](https://img.shields.io/badge/License-EPL_1.0-red.svg)'
        let badge;
        if(answers.license == 'MIT'){badge = mit};
        if(answers.license == 'GNU'){badge = gnu};
        if(answers.license == 'Eclipse'){badge = eclipse};
        const markdown =   `## Project Title: ${answers.name} ${badge}
Author: ${answers.author}
----------------------------------

## Description: 

${answers.description}
----------------------------------

## Table Of Contents

[Installation](#Installation)

[Usage](#Usage)

[License](#License)

[Contributing](#Contributing)

[Tests](#Tests)

[Questions](#Questions)


----------------------------------
<a id="Installation"></a>

## Installation

Installation Instructions
${answers.install}
----------------------------------
<a id="Usage"></a>

## Usage

Here are usage instructions for this app:
${answers.usage}
----------------------------------
<a id="License"></a>

## License

The content of this Project is licensed under the ${answers.license} License. ${badge}
----------------------------------
<a id="Contributing"></a>

## Contributing

The below people contributed to this project:
${answers.contributors}
----------------------------------
<a id="Tests"></a>

## Tests

These tests were run:
${answers.tests}
----------------------------------
<a id="Questions"></a>

## Questions

If you have any questions, please contact me!
Email: ${answers.email}
Github: [${answers.github}](https://github.com/${answers.github})

### README Generated by [ReadMeGenerator](https://github.com/AliBakerCodes/ReadMeGenerator)
    `
        fs.writeFile(filename, markdown, (err) =>
          err ? console.log(err) : console.log('Success!')
        );
}

init();