const inquirer = require('inquirer');
const fs = require('fs');
inquirer
  .prompt([
    {
        type: 'input',
        name: 'name',
        message: 'Project Name?',
      },
    {
      type: 'input',
      name: 'author',
      message: 'Project Author Name?',
    },
    {
      type: 'input',
      message: 'Give a short Description of your Project',
      name: 'description',
    },
    {
        type: 'input',
        name: 'install',
        message: 'What are the installation instructions?',
    },
    {
        type: 'list',
        name: 'license',
        message: 'Select the License for this Project',
        choices:['MIT','GNU','Eclipse']
    },
    {
        type: 'input',
        name: 'install',
        message: 'What are the installation instructions?',
    },
    {
        type: "loop",
        name: "contributors",
        message: "Add another Contributor?",
        questions: [
            {
                type: "input",
                name: "contribName",
                message: "Enter Contributor Name",
            }
        ],
    },
    {
        type: "loop",
        name: "tests",
        message: "Add another Test?",
        questions: [
            {
                type: "input",
                name: "test",
                message: "Enter a test",
            }
        ],
    },
    {
        type: 'input',
        name: 'email',
        message: 'Email?',
    },
    {
        type: 'input',
        name: 'github',
        message: 'Github Username?',
    }
  ])
  .then((data) => {
    const filename = `README-Generated.md`;
    const mit='[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)'
    const gnu='[![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)'
    const eclipse='[![License](https://img.shields.io/badge/License-EPL_1.0-red.svg)](https://opensource.org/licenses/EPL-1.0)'
    let badge;
    if(data.license == 'MIT'){badge = mit};
    if(data.license == 'GNU'){badge = gnu};
    if(data.license == 'Eclipse'){badge = eclipse};
    const markdown =   `
## Project Title: ${data.name}
Author: ${data.author}
${badge}
----------------------------------
## Description: 
${data.description}
----------------------------------
## Table Of Contents
[Installation](#Installation)

[Usage](#Usage)

[License](#License)

[Contributing](#Contributing)

[Tests](#Tests)

[Questions](#Questions)


----------------------------------
<a id="Installation"></a>
## Installation
Installation Instructions
${data.install}
----------------------------------
<a id="Usage"></a>
## Usage
Here are usage instructions for this app:
${data.usage}
----------------------------------
<a id="License"></a>
## License
The content of this Project is licensed under the ${data.license} License. ${badge}
----------------------------------
<a id="Contributing"></a>
## Contributing
The below people contributed to this project:
${contributors}
----------------------------------
<a id="Tests"></a>
## Tests
These tests were run:
${tests}
----------------------------------
<a id="Questions"></a>
## Questions
If you have any questions, please contact me!
Email: ${email}
Github: [${github}](https://github.com/${github})

### README Generated by [ReadMeGenerator](https://github.com/AliBakerCodes/ReadMeGenerator)
`
    fs.writeFile(filename, markdown, (err) =>
      err ? console.log(err) : console.log('Success!')
    );
  });